version: 47
jobs:
- name: maven build
  steps:
  - type: CommandStep
    name: maven
    runInContainer: false
    interpreter:
      type: DefaultInterpreter
      commands: |
        mvn clean build
    runAs: 0:0
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
