package dev.dominikbreu.spoonmcp.extractor.sourcefacts;

public enum SourceEvidence {
    DIRECT_TYPE_REFERENCE,
    FIELD_INJECTION,
    CONSTRUCTOR_INJECTION,
    METHOD_INJECTION,
    LOCAL_ASSIGNMENT,
    FIELD_ASSIGNMENT,
    METHOD_RETURNS_FIELD,
    METHOD_RETURNS_PARAMETER,
    METHOD_RETURNS_LOCAL,
    METHOD_RETURNS_INVOCATION,
    CONSTRUCTOR_CALL,
    POLYMORPHIC_IMPLEMENTATION,
    ANNOTATION_VALUE,
    CONFIG_VALUE,
    UNRESOLVED_NO_CLASSPATH,
    NAMING_HINT
}
